const CardsData = [
  {
    id: 1,
    title: "Wiring Leds",
    image_url: "images/wiring_leds.png",
    desc: "Wiring Leds",
    ref1: "https://www.instructables.com/LEDs-for-Beginners/",
    ref2: "https://www.ledsupply.com/blog/wiring-leds-correctly-series-parallel-circuits-explained/",
  },
  {
    id: 2,
    title: "Diodes",
    image_url: "images/diodes.jpg",
    desc: "Diodes",
    ref1: "https://www.instructables.com/Diodes/",
    ref2: "https://www.allaboutcircuits.com/textbook/semiconductors/chpt-3/introduction-to-diodes-and-rectifiers/",
  },
  {
    id: 3,
    title: "Resistors",
    image_url: "images/resistors.png",
    desc: "Types and Shapes of Resistors",
    ref1: "https://www.instructables.com/Resistors/",
    ref2: "https://learn.sparkfun.com/tutorials/resistors/all",
  },
  {
    id: 4,
    title: "Inductors",
    image_url: "images/inductors.jpg",
    desc: "Types and Shapes of Inductors",
    ref1: "https://www.instructables.com/Inductors-the-Basics/",
    ref2: "https://www.electricity-magnetism.org/inductors/",
  },

  {
    id: 5,
    title: "Capacitors",
    image_url: "images/capacitors.png",
    desc: "Types and Shapes of Capacitors",
    ref1: "https://www.instructables.com/Capacitors/",
    ref2: "https://www.electricity-magnetism.org/capacitors/",
  },

  {
    id: 6,
    title: "Sensors",
    image_url: "images/sensors.jpg",
    desc: "Types and Shapes of Transistors",
    ref1: "https://www.instructables.com/Transistors/",
    ref2: "https://www.electricity-magnetism.org/transistors/",
  },
  {
    id: 7,
    title: "Motors",
    image_url: "images/motors.png",
    desc: "Types and Shapes of Motors",
    ref1: "https://www.instructables.com/Motors/",
    ref2: "https://www.electricity-magnetism.org/motors/",
  },
  {
    id: 8,
    title: "3 Legs",
    image_url: "images/legs_3.jpg",
    desc: "3 Legs components",
    ref1: "https://www.instructables.com/3-Legs/",
    ref2: "https://www.electricity-magnetism.org/3-legs/",
  },
  {
    id: 9,
    title: "pwoer bench",
    image_url: "images/power_bench_wiring_1.jpg",
    desc: "power bench wiring - 1",
    ref1: "https://www.instructables.com/Power-Bench-Wiring-1/",
    ref2: "https://www.electricity-magnetism.org/power-bench-wiring-1/",
  },
  {
    id: 12,
    title: "Variable Resistors",
    image_url: "images/variable_resistors.jpg",
    desc: "power bench wiring - 4",
    ref1: "https://www.instructables.com/Power-Bench-Wiring-4/",
    ref2: "https://www.electricity-magnetism.org/power-bench-wiring-4/",
  },
];

export default CardsData;
